# Vectors and Matrices in Numpy - Lab

## Introduction

In this lab, you'll solve some simple matrix creation and manipulation exercises based on what you've learned so far in this section. The key takeaway here is to be able to understand how to use indexing with matrices and vectors while applying some basic operations.

## Objectives

In this lab you will: 

- Find the shape of vectors and matrices 
- Access and manipulate individual scalar components of a matrix 
- Create vectors and matrices using Numpy and Python

## 1. Define two arrays $A$  with shape $ (4 \times 2)$ and $B$ with shape $(2 \times 3)$ 
So    $A =    
  \left[ {\begin{array}{cc}
   1402 & 191 \\
   1371 &  821\\
   949 &  1437 \\
   147 & 1448 \\
  \end{array} }\right]
$
and
$
B =    
  \left[ {\begin{array}{ccc}
   1 & 2 & 3 \\
   4 & 5 & 6\\
  \end{array} }\right]
$

In [4]:
import numpy as np
A = np.array([[1402,191],
             [1371,821],
             [949,1437],
             [147,1448]])
B = np.array([[1,2,3],
              [4,5,6]])

## 2. Print the dimensions of $A$ and $B$ 

In [6]:
print(A.shape)
print(B.shape)

(4, 2)
(2, 3)


## 3. Print elements from $A$

Print the following elements from $A$: 

* First row and first column
* First row and second column
* Third row and second column
* Fourth row and first column

In [8]:
print(A[0,0])
print(A[0,1])
print(A[2,1])
print(A[3,0])

1402
191
1437
147


## 4. Write a routine to populate a matrix with random data
* Create an $(3 \times 3)$ Numpy array with all zeros (use `np.zeros()`)
* Access each location $(i,j)$ of this matrix and fill in random values between the range 1 and 10 

In [26]:
# Code here
rand_array = np.zeros((3,3))
for num in range(len(rand_array)**2):
    i = num%3
    j = num//3
    rand_array[i,j] = np.random.randint(1, 11)
rand_array   

array([[ 6.,  4.,  8.],
       [ 1.,  3.,  4.],
       [ 5., 10.,  9.]])

In [27]:
def rand_array(size):
    rd_arr = np.zeros((size,size))
    for num in range(len(rd_arr)**2):
        i = num%size
        j = num//size
        rd_arr[i,j] = np.random.randint(1, 11)
    return rd_arr  

## 5. Turn the above routine into a function
* Create two $(4 \times 4)$ zero-valued matrices and fill with random data using the function
* Add the matrices together in Numpy 
* Print the results

In [28]:
R = rand_array(4)
print(R)
K = rand_array(4)
print(K)
print(R+K)

[[10.  5.  9. 10.]
 [ 1.  5.  3.  9.]
 [ 5.  2. 10.  3.]
 [ 5.  7.  7.  3.]]
[[ 7.  6. 10.  7.]
 [ 2.  2.  4.  7.]
 [ 7.  9.  5.  6.]
 [ 5. 10.  6.  7.]]
[[17. 11. 19. 17.]
 [ 3.  7.  7. 16.]
 [12. 11. 15.  9.]
 [10. 17. 13. 10.]]


## Summary 

In this lab, we saw how to create and manipulate vectors and matrices in Numpy. We shall now move forward to learning more complex operations including dot products and matrix inversions.  